<a href="https://colab.research.google.com/github/SuryaPrakashBolloju/SuryaPrakashBolloju/blob/main/suryaprakash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Given a 2D array arr, extract the second column.
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr[:, 1])

[2 5 8]


In [ ]:
#Extract a subarray from a 3x3 matrix that includes the first and second rows and the second and third columns.
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
subarray = matrix[:2, 1:]
print(subarray)

[[2 3]
 [5 6]]


In [ ]:
#Given a 3D array, transpose the first and second dimensions.
import numpy as np
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]],
                     [[13, 14, 15], [16, 17, 18]]])
transposed_array = array_3d.T
print(transposed_array)

[[[ 1  7 13]
  [ 4 10 16]]

 [[ 2  8 14]
  [ 5 11 17]]

 [[ 3  9 15]
  [ 6 12 18]]]


In [ ]:
# Transpose a 2D array and then extract a specific row from the transposed result

import numpy as np
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
transposed_array = array_2d.T
row_index = 1
extracted_row = transposed_array[row_index]
print("Original 2D Array:")
print(array_2d)
print("\nTransposed 2D Array:")
print(transposed_array)
print("\nExtracted Row from Transposed Array (Index {}):".format(row_index))
print(extracted_row)

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed 2D Array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Extracted Row from Transposed Array (Index 1):
[2 5 8]


In [ ]:
# Given a 3D array, extract a 2x2 matrix from the second "layer" (2D array) using appropriate indexing.
import numpy as np
arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                 [[7, 8, 9],
                 [10, 11, 12]],
                 [[13, 14, 15],
                 [16, 17, 18]]])
extracted_matrix = arr[1, :2, :2]

print("Original 3D Array:")
print(arr)
print("\nExtracted 2x2 Matrix from the Second Layer :")
print(extracted_matrix)

Original 3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

Extracted 2x2 Matrix from the Second Layer :
[[ 7  8]
 [10 11]]
